CaptureTheFart/src/me/bobthe28th/capturethefart/Main.java
=> More trolling

CaptureTheFart/src/me/bobthe28th/capturethefart/Main.java, CaptureTheFart/src/me/bobthe28th/capturethefart/ctf/items/Wizard/WizStickIce.java, CaptureTheFart/src/me/bobthe28th/capturethefart/ctf/items/Wizard/WizStickWind.java
=> Make getLookedAtPlayer into its own function

CaptureTheFart/src/me/bobthe28th/capturethefart/ctf/CTFCommands.java
Makes all t to t6 Player into one target
=> Removes extra var instances of target

CaptureTheFart/src/me/bobthe28th/capturethefart/ctf/items/Wizard/WizStickIce.java
=> Fixes ice chunk dropping item

src/me/bobthe28th/capturethefart/ctf/deathMessages.json
=> Demolitionist TNT death messages

src/me/bobthe28th/capturethefart/ctf/deathMessages.json
For all custom damage and default damage causes.
=> Adds new death messages

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/deathMessages.json, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizBookIce.java
Sets their y velocity to 0 on the first tick.
Closes #9 
Also Closes #11
=> Fixes(?) player falling through ice walk and demolitionist (this should be 2 different pr but my brain poopy)

src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWool.java
=> Fixes wool displaying as wood

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWood.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWool.java, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalIron.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFBuildUpItem.java
New ArrayList where blocks can be added.
Closes #21
=> Makes ctf breakable blocks

src/me/bobthe28th/capturethefart/ctf/CTFClass.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/classes/Paladin.java, src/me/bobthe28th/capturethefart/ctf/classes/Wizard.java
Why did I make plugin and player var for each class? I couldn't tell ya
=> Moves CTFPlayer to base CTFClass and removes extra instances

src/me/bobthe28th/capturethefart/ctf/classes/Archer.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcGhostArrow.java
=> Doesn't look like ghost arrow is possible

src/me/bobthe28th/capturethefart/ctf/deathMessages.json
=> what the hell

src/me/bobthe28th/capturethefart/ctf/CTFDeathMessages.java, src/me/bobthe28th/capturethefart/ctf/deathMessages.json
=> Fixes stupid comma (hotfix)

src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java
Should fix items still having cooldowns when switching class
Closes #35
=> Remove items when setting class

src/me/bobthe28th/capturethefart/Main.java
=> Halfs demolitionists self knockback with TNT

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemTNT.java
Also fixes cooldown not firing
=> Sets Demo self knockback div to 1.5 (was 1 then 2)

src/me/bobthe28th/capturethefart/ctf/deathMessages.json
Because I die a lot to falling
=> Falling death messages

src/me/bobthe28th/capturethefart/ctf/items/demo/DemArrow.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemBow.java
sets custom model data to correct values
=> Demo custom model data

src/me/bobthe28th/capturethefart/ctf/classes/Demo.java
=> Particles for bomb arrow(rocket)

src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java
=> Fire stick range correction

src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemBow.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFOtherItem.java
=> Makes new ctfitem where all it does it do other items display cooldowns

src/plugin.yml
=> api-version 1.18

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickWind.java
=> Flag on head

src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/classes/Archer.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/classes/Paladin.java, src/me/bobthe28th/capturethefart/ctf/classes/Wizard.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcBow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/testarrow.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiAxe.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiShears.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWood.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWool.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemArrow.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemBow.java, src/me/bobthe28th/capturethefart/ctf/items/demo/DemTNT.java, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalIron.java, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalSword.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizBookFire.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizBookIce.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizBookWind.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickIce.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickWind.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFBuildUpItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFDoubleCooldownItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFOtherItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFOtherItemSlot.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFStackCooldownItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFToolCooldownItem.java
=> Archer arrows functionality

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFClass.java, src/me/bobthe28th/capturethefart/ctf/CTFFlag.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/CTFTeam.java, src/me/bobthe28th/capturethefart/ctf/classes/Archer.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/classes/Paladin.java, src/me/bobthe28th/capturethefart/ctf/classes/Wizard.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWood.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWool.java
Adds armor system, cosmetic default armor of team color and such
=> Armor System

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFClass.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWood.java, src/me/bobthe28th/capturethefart/ctf/items/builder/BuiWool.java, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalIron.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFBuildUpItem.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFItem.java
=> Builder can get their blocks back

src/plugin.yml
Should be like 0.8 by now but I forgor
=> Version 0.7

src/me/bobthe28th/capturethefart/ctf/CTFCommands.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java
Still need wizard to be split into subclasses #17
=> Builder and Demo hat

src/me/bobthe28th/capturethefart/ctf/CTFClass.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/classes/Assassin.java
=> Remove invis on damage

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFCommands.java, src/me/bobthe28th/capturethefart/ctf/CTFTabCompletion.java, src/plugin.yml
=> Music system

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFClass.java, src/me/bobthe28th/capturethefart/ctf/CTFCommands.java, src/me/bobthe28th/capturethefart/ctf/classes/Alchemist.java, src/me/bobthe28th/capturethefart/ctf/classes/Archer.java, src/me/bobthe28th/capturethefart/ctf/classes/Assassin.java, src/me/bobthe28th/capturethefart/ctf/classes/Builder.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/classes/Paladin.java, src/me/bobthe28th/capturethefart/ctf/classes/WizardFire.java, src/me/bobthe28th/capturethefart/ctf/classes/WizardIce.java, src/me/bobthe28th/capturethefart/ctf/classes/WizardWind.java
fakeClass() sends packets spawning a fake player with class armor
=> Fake player class

src/me/bobthe28th/capturethefart/ctf/items/assassin/AssPotion.java
=> Particles as assassin

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/deathMessages.json, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalHammer.java
Adds the ability for the paladin to throw their hammer
=> Paladin hammer throw

README.md
=> Edit README.md to have correct name

src/me/bobthe28th/capturethefart/ctf/classes/Archer.java
Adds jump boost potion effect to the archer class
Closes #93
=> Archer Passive

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizBookFire.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java
Fixes #92 
Adds Fireball ability
Adds attack boost ability
=> Fire wizard abilities

src/me/bobthe28th/capturethefart/Main.java
=> Remove death message reason broadcast

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFFlag.java, src/me/bobthe28th/capturethefart/ctf/CTFGameController.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/CTFTeam.java, src/me/bobthe28th/capturethefart/ctf/ScoreboardRow.java, src/me/bobthe28th/capturethefart/ctf/ScoreboardRowGlobal.java, src/me/bobthe28th/capturethefart/ctf/classes/Alchemist.java, src/me/bobthe28th/capturethefart/ctf/classes/Assassin.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcDamage.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcJump.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcPoison.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcRegen.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcSlow.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcSpeed.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcStrength.java, src/me/bobthe28th/capturethefart/ctf/items/alchemist/AlcWeak.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickWind.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFItem.java
Adds a scoreboard that shows scores, flag status, kills, and deaths
Adds respawn system
=> Scoreboard + respawn

src/me/bobthe28th/capturethefart/ctf/items/paladin/PalHammer.java
=> hammer throw animation

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java, src/me/bobthe28th/capturethefart/ctf/classes/Demo.java, src/me/bobthe28th/capturethefart/ctf/damage/CTFDamage.java, src/me/bobthe28th/capturethefart/ctf/damage/CTFDamageCause.java, src/me/bobthe28th/capturethefart/ctf/deathMessages.json, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcGhostArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcPoisonArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcSonicArrow.java, src/me/bobthe28th/capturethefart/ctf/items/paladin/PalHammer.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickWind.java
=> Fixes death messages

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFCommands.java, src/me/bobthe28th/capturethefart/ctf/CTFTabCompletion.java
Fixes #112 
Adds music queue system to play multiple songs in a row
=> Music queue system

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/items/wizard/WizStickFire.java, src/me/bobthe28th/capturethefart/ctf/itemtypes/CTFItem.java
=> Wizard fire staff no hit

src/me/bobthe28th/capturethefart/ctf/classes/Archer.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcGhostArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcPoisonArrow.java, src/me/bobthe28th/capturethefart/ctf/items/archer/ArcSonicArrow.java
Makes archer have only one of each arrow and make normal arrow infinite.
=> Archer Rework

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/classes/Assassin.java, src/me/bobthe28th/capturethefart/ctf/items/assassin/AssSmoke.java
=> Assassin smoke bomb

src/me/bobthe28th/capturethefart/Main.java, src/me/bobthe28th/capturethefart/ctf/CTFCommands.java, src/me/bobthe28th/capturethefart/ctf/CTFTabCompletion.java, src/me/bobthe28th/capturethefart/ctf/items/assassin/AssPotion.java, src/me/bobthe28th/capturethefart/ctf/items/assassin/AssSmoke.java, src/plugin.yml
Explosions now destroy builders blocks
=> Classhelp and explosions
